# Kali NetHunter Kernel Features
CONFIG_CFG80211=y
CONFIG_MAC80211=y
CONFIG_MAC80211_MESH=y
CONFIG_MAC80211_RC_MINSTREL=y
CONFIG_CFG80211_WEXT=y
CONFIG_NL80211_TESTMODE=y

# External USB Wi-Fi Drivers
CONFIG_ATH_CARDS=m
CONFIG_ATH9K_HTC=m
CONFIG_CARL9170=m
CONFIG_RT2X00=m
CONFIG_RT2800USB=m
CONFIG_RTL8187=m
CONFIG_8812AU=m
CONFIG_RTL8821CU=m

# USB Gadget & HID BadUSB
CONFIG_USB_CONFIGFS_F_HID=y
CONFIG_USB_F_HID=y
CONFIG_USB_G_HID=m

# Bluetooth RFCOMM
CONFIG_BT_HCIBTUSB=m
CONFIG_BT_HCIUART=m
CONFIG_BT_RFCOMM=y

# Security bypasses
CONFIG_SECURITY_DEFEX=n
CONFIG_UH_RKP=n
CONFIG_KNOX_KAP=n
CONFIG_TIMA=n
CONFIG_SEC_RESTRICT_ROOTING=n
CONFIG_INTEGRITY=n
